import express from "express";
import {Request,Response} from "express";
import * as parser from "body-parser";
import * as mongoclient from "mongoose";
 const port =3000;
 const hostname="localhost";
 const app=express();
 let userModel:any=null;
 app.listen(port,hostname,function()//Backend to frontend connection
 {
     console.log("server started");
 });

 function connectDb()   //connection to mongodb
 {
     mongoclient.connect("mongodb://localhost:27017/myDb",{ useNewUrlParser: true })
     .then(function(resp:any){console.log("connected successfully")})
     .catch(function(err:any){console.log(err)});
 }
 connectDb()     
 function createUserFunction()
 {  
     //let schema=mongoclient.Schema;
     let userSchema=new mongoclient.Schema(
         {
             name:{
                 type:String,
                 required:true,
                 unique:true
             },
             email : String,
             mobile: String
         }
     );//userSchema can have paramter or field name can have following values eg:--> name:{type:string,required:true,default:"somevalue",unique:true}
    userModel=mongoclient.model("user",userSchema);//To register my userSchema with db . This part will return refernce to db
 }
 createUserFunction()
 app.use(parser.json());//config to use bodyparser
 app.use(parser.urlencoded({extended:false}));

 app.get('/',function(req:Request,res:Response)
 {
     console.log("sever is running")
     console.log(req.url)
     res.send("Hello world")
 });
 app.get('/profile',function(req:Request,res:Response)
 {
     
     console.log(req.url)
     res.send("Profile service")
     
 });
 app.get('/details',function(req:Request,res:Response)
 {
     console.log(req.url);
     console.log(req.query);
     console.log(req.params);
     res.send("Details service")
     
 });
 app.get('/details/:Id',function(req:Request,res:Response)
 {
     console.log(req.url);
     console.log(req.query);
     console.log(req.params);
     res.send("Details service")
     
 });
 app.post('/register',function(req:Request,res:Response)
 {
     console.log(req.body);
     res.send(req.body)

 }
 );
 app.post('/registerInDb',function(req:Request,res:Response)
    {
        let user=new userModel(req.body);
        user.save();
        res.send("Successfully registered");
    });
app.get('/getRegisteredUser',function(req:Request,res:Response)
    {
       userModel.find().then((data:any)=>{
        res.send(data)
        })
        
    })
    app.get('/getRegUserByEmail',function(req:Request,res:Response)//using query "http://localhost:3000/getRegUserByEmail?email=ksandy541@gmail.com"
    {
        userModel.find({email:req.query.email}).then((data:any)=>
        {
            res.send(data)
        })
    }
    )
    app.get('/getRegUserByEmail/:email',function(req:Request,res:Response)//using parameter "http://localhost:3000/getRegUserByEmail/ksandy541@gmail.com"
    {
        console.log(req.params)
        userModel.find({id:req.params.email}).then((data:any)=>
        {
            res.send(data)
        })
    }
    )
    app.get('/getRegUserById/:id',function(req:Request,res:Response)//using parameter "http://localhost:3000/getRegUserById/5ccece17cbc1ce1970e6cdaa"
    {
        console.log(req.params)
        userModel.findOne().then((data:any)=> // here no need of any value inside the findOne since it is id which is autogenerated in db {email:req.params.email}
        {
            res.send(data)
        })
    }
    )
